service: sls-multicloud
frameworkVersion: '2'
provider:
  name: aws
  region: eu-west-1
  runtime: dotnetcore3.1
package:
  individually: true
functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
      - http:
          path: /hello-world
          method: GET
          integration: lambda
          cors: true
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip